import { PortfolioProject } from '../../core/models/project.model';

export const PROJECTS: PortfolioProject[] = [
  {
    order: 10,
    id: 'tic-tac-toe',
    titleKey: 'PROJECTS.TIC_TAC_TOE.TITLE',
    summaryKey: 'PROJECTS.TIC_TAC_TOE.SUMMARY',
    categoryKey: 'CATEGORIES.GAMES',
    tags: ['Angular', 'TypeScript', 'State'],
    status: 'ready',
    image: 'assets/project-covers/tic-tac-toe.png',
    route: '/admin/projects/tic-tac-toe',
    updatedAt: '2026-06-17',
    createdAt: '2026-06-17',
    difficulty: 'beginner',
    repositoryUrl: null,
    demoUrl: null
  },
  {
    order: 20,
    id: 'calculator',
    titleKey: 'PROJECTS.CALCULATOR.TITLE',
    summaryKey: 'PROJECTS.CALCULATOR.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Keyboard', 'SCSS'],
    status: 'ready',
    image: 'assets/project-covers/calculator.png',
    route: '/admin/projects/calculator',
    updatedAt: '2026-06-17',
    createdAt: '2026-06-17',
    difficulty: 'beginner',
    repositoryUrl: null,
    demoUrl: null
  },
  {
    order: 30,
    id: 'hang-man',
    titleKey: 'PROJECTS.HANG_MAN.TITLE',
    summaryKey: 'PROJECTS.HANG_MAN.SUMMARY',
    categoryKey: 'CATEGORIES.GAMES',
    tags: ['Angular', 'TypeScript', 'Signals', 'Game UI'],
    status: 'ready',
    image: 'assets/project-covers/hang-man.png',
    route: '/admin/projects/hang-man',
    updatedAt: '2026-06-17',
    createdAt: '2026-06-17',
    difficulty: 'intermediate',
    repositoryUrl: null,
    demoUrl: null
  },
  {
    order: 40,
    id: 'weather',
    titleKey: 'PROJECTS.WEATHER.TITLE',
    summaryKey: 'PROJECTS.WEATHER.SUMMARY',
    categoryKey: 'CATEGORIES.API',
    tags: ['Angular', 'TypeScript', 'API State', 'Filters'],
    status: 'ready',
    image: 'assets/project-covers/weather.png',
    route: '/admin/projects/weather',
    updatedAt: '2026-06-17',
    createdAt: '2026-06-17',
    difficulty: 'intermediate',
    repositoryUrl: null,
    demoUrl: null
  },
  {
    order: 50,
    id: 'music-event',
    titleKey: 'PROJECTS.MUSIC_EVENT.TITLE',
    summaryKey: 'PROJECTS.MUSIC_EVENT.SUMMARY',
    categoryKey: 'CATEGORIES.EVENTS',
    tags: ['Angular', 'PrimeNG', 'Modals', 'Filters'],
    status: 'ready',
    image: 'assets/project-covers/music-event.png',
    route: '/admin/projects/music-event',
    updatedAt: '2026-06-17',
    createdAt: '2026-06-17',
    difficulty: 'intermediate',
    repositoryUrl: null,
    demoUrl: null
  },
  {
    order: 60,
    id: 'javascript-quiz',
    titleKey: 'PROJECTS.JAVASCRIPT_QUIZ.TITLE',
    summaryKey: 'PROJECTS.JAVASCRIPT_QUIZ.SUMMARY',
    categoryKey: 'CATEGORIES.GAMES',
    tags: ['Angular', 'TypeScript', 'Quiz', 'Timer'],
    status: 'ready',
    image: 'assets/project-covers/javascript-quiz.png',
    route: '/admin/projects/javascript-quiz',
    updatedAt: '2026-06-22',
    createdAt: '2026-06-22',
    difficulty: 'intermediate',
    repositoryUrl: null,
    demoUrl: null
  },
  {
    order: 70,
    id: 'todo-list',
    titleKey: 'PROJECTS.TODO_LIST.TITLE',
    summaryKey: 'PROJECTS.TODO_LIST.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Forms', 'LocalStorage'],
    status: 'ready',
    image: 'assets/project-covers/todo-list.svg',
    route: '/admin/projects/todo-list',
    updatedAt: '2026-06-24',
    createdAt: '2026-06-24',
    difficulty: 'beginner',
    repositoryUrl: null,
    demoUrl: null
  },
  {
    order: 80,
    id: 'expense-tracker',
    titleKey: 'PROJECTS.EXPENSE_TRACKER.TITLE',
    summaryKey: 'PROJECTS.EXPENSE_TRACKER.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Chart.js', 'LocalStorage'],
    status: 'ready',
    image: 'assets/project-covers/expense-tracker.svg',
    route: '/admin/projects/expense-tracker',
    updatedAt: '2026-06-24',
    createdAt: '2026-06-24',
    difficulty: 'intermediate',
    repositoryUrl: null,
    demoUrl: null
  },
  {
    order: 90,
    id: 'technical-documentation',
    titleKey: 'PROJECTS.TECHNICAL_DOCUMENTATION.TITLE',
    summaryKey: 'PROJECTS.TECHNICAL_DOCUMENTATION.SUMMARY',
    categoryKey: 'CATEGORIES.DOCUMENTATION',
    tags: ['Angular', 'TypeScript', 'Docs', 'Architecture'],
    status: 'ready',
    image: 'assets/project-covers/technical-documentation.svg',
    route: '/admin/projects/technical-documentation',
    updatedAt: '2026-06-25',
    createdAt: '2026-06-25',
    difficulty: 'beginner',
    repositoryUrl: null,
    demoUrl: null
  }
];
