import { PortfolioProject } from '../../core/models/project.model';

const REPOSITORY_BASE_URL =
  'https://github.com/AngjelSpasovski/projects-hub/tree/master/src/app/features/projects';

export const PROJECTS: PortfolioProject[] = [
  {
    order: 10,
    id: 'tic-tac-toe',
    titleKey: 'PROJECTS.TIC_TAC_TOE.TITLE',
    summaryKey: 'PROJECTS.TIC_TAC_TOE.SUMMARY',
    categoryKey: 'CATEGORIES.GAMES',
    tags: ['Angular', 'TypeScript', 'State'],
    status: 'ready',
    image: 'assets/project-covers/tic-tac-toe.png',
    route: '/admin/projects/tic-tac-toe',
    updatedAt: '2026-06-17',
    createdAt: '2026-06-17',
    difficulty: 'beginner',
    layout: 'compact',
    repositoryUrl: `${REPOSITORY_BASE_URL}/tic-tac-toe`,
    demoUrl: null
  },
  {
    order: 20,
    id: 'calculator',
    titleKey: 'PROJECTS.CALCULATOR.TITLE',
    summaryKey: 'PROJECTS.CALCULATOR.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Keyboard', 'SCSS'],
    status: 'ready',
    image: 'assets/project-covers/calculator.png',
    route: '/admin/projects/calculator',
    updatedAt: '2026-06-17',
    createdAt: '2026-06-17',
    difficulty: 'beginner',
    layout: 'compact',
    repositoryUrl: `${REPOSITORY_BASE_URL}/calculator`,
    demoUrl: null
  },
  {
    order: 30,
    id: 'hang-man',
    titleKey: 'PROJECTS.HANG_MAN.TITLE',
    summaryKey: 'PROJECTS.HANG_MAN.SUMMARY',
    categoryKey: 'CATEGORIES.GAMES',
    tags: ['Angular', 'TypeScript', 'Signals', 'Game UI'],
    status: 'ready',
    image: 'assets/project-covers/hang-man.png',
    route: '/admin/projects/hang-man',
    updatedAt: '2026-06-17',
    createdAt: '2026-06-17',
    difficulty: 'intermediate',
    layout: 'compact',
    repositoryUrl: `${REPOSITORY_BASE_URL}/hang-man`,
    demoUrl: null
  },
  {
    order: 40,
    id: 'weather',
    titleKey: 'PROJECTS.WEATHER.TITLE',
    summaryKey: 'PROJECTS.WEATHER.SUMMARY',
    categoryKey: 'CATEGORIES.API',
    tags: ['Angular', 'TypeScript', 'API State', 'Filters'],
    status: 'ready',
    image: 'assets/project-covers/weather.png',
    route: '/admin/projects/weather',
    updatedAt: '2026-06-25',
    createdAt: '2026-06-17',
    difficulty: 'intermediate',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/weather`,
    demoUrl: null
  },
  {
    order: 50,
    id: 'music-event',
    titleKey: 'PROJECTS.MUSIC_EVENT.TITLE',
    summaryKey: 'PROJECTS.MUSIC_EVENT.SUMMARY',
    categoryKey: 'CATEGORIES.EVENTS',
    tags: ['Angular', 'PrimeNG', 'Modals', 'Filters'],
    status: 'ready',
    image: 'assets/project-covers/music-event.png',
    route: '/admin/projects/music-event',
    updatedAt: '2026-06-17',
    createdAt: '2026-06-17',
    difficulty: 'intermediate',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/music-event`,
    demoUrl: null
  },
  {
    order: 60,
    id: 'javascript-quiz',
    titleKey: 'PROJECTS.JAVASCRIPT_QUIZ.TITLE',
    summaryKey: 'PROJECTS.JAVASCRIPT_QUIZ.SUMMARY',
    categoryKey: 'CATEGORIES.GAMES',
    tags: ['Angular', 'TypeScript', 'Quiz', 'Timer'],
    status: 'ready',
    image: 'assets/project-covers/javascript-quiz.png',
    route: '/admin/projects/javascript-quiz',
    updatedAt: '2026-06-22',
    createdAt: '2026-06-22',
    difficulty: 'intermediate',
    layout: 'compact',
    repositoryUrl: `${REPOSITORY_BASE_URL}/javascript-quiz`,
    demoUrl: null
  },
  {
    order: 70,
    id: 'todo-list',
    titleKey: 'PROJECTS.TODO_LIST.TITLE',
    summaryKey: 'PROJECTS.TODO_LIST.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Forms', 'LocalStorage'],
    status: 'ready',
    image: 'assets/project-covers/todo-list.svg',
    route: '/admin/projects/todo-list',
    updatedAt: '2026-06-24',
    createdAt: '2026-06-24',
    difficulty: 'beginner',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/todo-list`,
    demoUrl: null
  },
  {
    order: 80,
    id: 'expense-tracker',
    titleKey: 'PROJECTS.EXPENSE_TRACKER.TITLE',
    summaryKey: 'PROJECTS.EXPENSE_TRACKER.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Chart.js', 'LocalStorage'],
    status: 'ready',
    image: 'assets/project-covers/expense-tracker.svg',
    route: '/admin/projects/expense-tracker',
    updatedAt: '2026-06-24',
    createdAt: '2026-06-24',
    difficulty: 'intermediate',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/expense-tracker`,
    demoUrl: null
  },
  {
    order: 90,
    id: 'technical-documentation',
    titleKey: 'PROJECTS.TECHNICAL_DOCUMENTATION.TITLE',
    summaryKey: 'PROJECTS.TECHNICAL_DOCUMENTATION.SUMMARY',
    categoryKey: 'CATEGORIES.DOCUMENTATION',
    tags: ['Angular', 'TypeScript', 'Docs', 'Architecture'],
    status: 'ready',
    image: 'assets/project-covers/technical-documentation.svg',
    route: '/admin/projects/technical-documentation',
    updatedAt: '2026-06-25',
    createdAt: '2026-06-25',
    difficulty: 'beginner',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/technical-documentation`,
    demoUrl: null
  },
  {
    order: 100,
    id: 'movie-search',
    titleKey: 'PROJECTS.MOVIE_SEARCH.TITLE',
    summaryKey: 'PROJECTS.MOVIE_SEARCH.SUMMARY',
    categoryKey: 'CATEGORIES.API',
    tags: ['Angular', 'TypeScript', 'API State', 'Pagination'],
    status: 'ready',
    image: 'assets/project-covers/movie-search.svg',
    route: '/admin/projects/movie-search',
    updatedAt: '2026-06-25',
    createdAt: '2026-06-25',
    difficulty: 'intermediate',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/movie-search`,
    demoUrl: null
  },
  {
    order: 110,
    id: 'rest-countries',
    titleKey: 'PROJECTS.REST_COUNTRIES.TITLE',
    summaryKey: 'PROJECTS.REST_COUNTRIES.SUMMARY',
    categoryKey: 'CATEGORIES.API',
    tags: ['Angular', 'TypeScript', 'API State', 'LocalStorage'],
    status: 'ready',
    image: 'assets/project-covers/rest-countries.svg',
    route: '/admin/projects/rest-countries',
    updatedAt: '2026-06-25',
    createdAt: '2026-06-25',
    difficulty: 'intermediate',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/rest-countries`,
    demoUrl: null
  },
  {
    order: 120,
    id: 'currency-converter',
    titleKey: 'PROJECTS.CURRENCY_CONVERTER.TITLE',
    summaryKey: 'PROJECTS.CURRENCY_CONVERTER.SUMMARY',
    categoryKey: 'CATEGORIES.API',
    tags: ['Angular', 'TypeScript', 'API State', 'Validation'],
    status: 'ready',
    image: 'assets/project-covers/currency-converter.svg',
    route: '/admin/projects/currency-converter',
    updatedAt: '2026-06-25',
    createdAt: '2026-06-25',
    difficulty: 'intermediate',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/currency-converter`,
    demoUrl: null
  },
  {
    order: 130,
    id: 'quotes-api',
    titleKey: 'PROJECTS.QUOTES_API.TITLE',
    summaryKey: 'PROJECTS.QUOTES_API.SUMMARY',
    categoryKey: 'CATEGORIES.API',
    tags: ['Angular', 'TypeScript', 'API State', 'Animation', 'LocalStorage'],
    status: 'ready',
    image: 'assets/project-covers/quotes-api.svg',
    route: '/admin/projects/quotes-api',
    updatedAt: '2026-06-25',
    createdAt: '2026-06-25',
    difficulty: 'beginner',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/quotes-api`,
    demoUrl: null
  },
  {
    order: 140,
    id: 'sticky-notes',
    titleKey: 'PROJECTS.STICKY_NOTES.TITLE',
    summaryKey: 'PROJECTS.STICKY_NOTES.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Forms', 'LocalStorage'],
    status: 'ready',
    image: 'assets/project-covers/sticky-notes.svg',
    route: '/admin/projects/sticky-notes',
    updatedAt: '2026-06-25',
    createdAt: '2026-06-25',
    difficulty: 'beginner',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/sticky-notes`,
    demoUrl: null
  },
  {
    order: 150,
    id: 'grocery-list',
    titleKey: 'PROJECTS.GROCERY_LIST.TITLE',
    summaryKey: 'PROJECTS.GROCERY_LIST.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Forms', 'LocalStorage'],
    status: 'ready',
    image: 'assets/project-covers/grocery-list.svg',
    route: '/admin/projects/grocery-list',
    updatedAt: '2026-06-25',
    createdAt: '2026-06-25',
    difficulty: 'beginner',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/grocery-list`,
    demoUrl: null
  },
  {
    order: 160,
    id: 'project-planner',
    titleKey: 'PROJECTS.PROJECT_PLANNER.TITLE',
    summaryKey: 'PROJECTS.PROJECT_PLANNER.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Signals', 'Migration'],
    status: 'ready',
    image: 'assets/project-covers/project-planner.svg',
    route: '/admin/projects/project-planner',
    updatedAt: '2026-07-06',
    createdAt: '2026-07-06',
    difficulty: 'intermediate',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/project-planner`,
    demoUrl: null
  },
  {
    order: 170,
    id: 'odd-even',
    titleKey: 'PROJECTS.ODD_EVEN.TITLE',
    summaryKey: 'PROJECTS.ODD_EVEN.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Signals', 'Timing'],
    status: 'ready',
    image: 'assets/project-covers/odd-even.svg',
    route: '/admin/projects/odd-even',
    updatedAt: '2026-07-08',
    createdAt: '2026-07-08',
    difficulty: 'beginner',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/odd-even`,
    demoUrl: null
  },
  {
    order: 180,
    id: 'dev-logger',
    titleKey: 'PROJECTS.DEV_LOGGER.TITLE',
    summaryKey: 'PROJECTS.DEV_LOGGER.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Forms', 'Signals'],
    status: 'ready',
    image: 'assets/project-covers/dev-logger.svg',
    route: '/admin/projects/dev-logger',
    updatedAt: '2026-07-08',
    createdAt: '2026-07-08',
    difficulty: 'beginner',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/dev-logger`,
    demoUrl: null
  },
  {
    order: 190,
    id: 'recipe-book',
    titleKey: 'PROJECTS.RECIPE_BOOK.TITLE',
    summaryKey: 'PROJECTS.RECIPE_BOOK.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Reactive Forms', 'Signals'],
    status: 'ready',
    image: 'assets/project-covers/recipe-book.svg',
    route: '/admin/projects/recipe-book',
    updatedAt: '2026-07-09',
    createdAt: '2026-07-09',
    difficulty: 'intermediate',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/recipe-book`,
    demoUrl: null
  },
  {
    order: 200,
    id: 'flashcards',
    titleKey: 'PROJECTS.FLASHCARDS.TITLE',
    summaryKey: 'PROJECTS.FLASHCARDS.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Forms', 'LocalStorage'],
    status: 'ready',
    image: 'assets/project-covers/flashcards.svg',
    route: '/admin/projects/flashcards',
    updatedAt: '2026-07-10',
    createdAt: '2026-07-10',
    difficulty: 'intermediate',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/flashcards`,
    demoUrl: null
  },
  {
    order: 210,
    id: 'timer',
    titleKey: 'PROJECTS.TIMER.TITLE',
    summaryKey: 'PROJECTS.TIMER.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Signals', 'LocalStorage'],
    status: 'ready',
    image: 'assets/project-covers/timer.svg',
    route: '/admin/projects/timer',
    updatedAt: '2026-07-10',
    createdAt: '2026-07-10',
    difficulty: 'beginner',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/timer`,
    demoUrl: null
  },
  {
    order: 220,
    id: 'digital-clock',
    titleKey: 'PROJECTS.DIGITAL_CLOCK.TITLE',
    summaryKey: 'PROJECTS.DIGITAL_CLOCK.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Signals', 'Intl'],
    status: 'ready',
    image: 'assets/project-covers/digital-clock.svg',
    route: '/admin/projects/digital-clock',
    updatedAt: '2026-07-10',
    createdAt: '2026-07-10',
    difficulty: 'beginner',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/digital-clock`,
    demoUrl: null
  },
  {
    order: 230,
    id: 'tip-calculator',
    titleKey: 'PROJECTS.TIP_CALCULATOR.TITLE',
    summaryKey: 'PROJECTS.TIP_CALCULATOR.SUMMARY',
    categoryKey: 'CATEGORIES.UTILITIES',
    tags: ['Angular', 'TypeScript', 'Forms', 'Validation'],
    status: 'ready',
    image: 'assets/project-covers/tip-calculator.svg',
    route: '/admin/projects/tip-calculator',
    updatedAt: '2026-07-13',
    createdAt: '2026-07-13',
    difficulty: 'beginner',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/tip-calculator`,
    demoUrl: null
  },
  {
    order: 240,
    id: 'memory-game',
    titleKey: 'PROJECTS.MEMORY_GAME.TITLE',
    summaryKey: 'PROJECTS.MEMORY_GAME.SUMMARY',
    categoryKey: 'CATEGORIES.GAMES',
    tags: ['Angular', 'TypeScript', 'Signals', 'Game UI'],
    status: 'ready',
    image: 'assets/project-covers/memory-game.svg',
    route: '/admin/projects/memory-game',
    updatedAt: '2026-07-13',
    createdAt: '2026-07-13',
    difficulty: 'beginner',
    layout: 'wide',
    repositoryUrl: `${REPOSITORY_BASE_URL}/memory-game`,
    demoUrl: null
  }
];
